[package]
name = "bailey"
version = "0.1.0"
authors = ["Jose Narvaez <goyox86@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.11.0"

[dependencies]
lalrpop-util = "0.11.0"
getopts = "0.2"
